version: "3.1"

services:
   
   traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=lriccombene@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: fei2020
      MYSQL_ROOT_PASSWORD: fei2020

    ports:
            - 4000:3306
    volumes:
            - ./mysqldata:/var/lib/mysql:delegated
    
  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: fei2020
    ports:
      - 8001:80

  app:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
    environment:
      DB_DATABASE: fei2020
      DB_PASSWORD: fei2020
      DB_HOST: db
      PRODUCCION: 0
      PHP_ENABLE_XDEBUG: 1
      PHP_USER_ID: 1000
    
    labels:

      - "traefik.enable=true"
      - "traefik.http.routers.apache2_router_http.rule=Host(`ambiente2020.ddns.net`)"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.apache2_router_http.middlewares=https_redirect"
      - "traefik.http.routers.apache2_router_https.rule=Host(`ambiente2020.ddns.net`)"
      - "traefik.http.routers.apache2_router_https.tls"
      - "traefik.http.routers.apache2_router_https.tls.certresolver=leresolver"

      - "traefik.port=80"

    ports:  
      - 8000:80

      
