version: "3.1"

services:
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: fei2020
      MYSQL_ROOT_PASSWORD: fei2020
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    
  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: lkjlkjasd
    ports:
      - 8001:80

  app:
#    image: yiisoftware/yii2-php:7.1-apache
    image: lucianomelman/yii2-feifei2020:1
    build: ./build
    restart: always
    environment:
      DB_DATABASE: fei2020
      DB_PASSWORD: fei2020
      DB_HOST: db
      PRODUCCION: 0
      PHP_ENABLE_XDEBUG: 1
      PHP_USER_ID: 1000
    ports:  
      - 8000:80

      
